apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-web
  labels:
    app: ai-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-web
  template:
    metadata:
      labels:
        app: ai-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: 10.0.88.201
      containers:
      - name: ai-web
        image: aiweb:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi" 