apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-web
  labels:
    app: ai-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-web
  template:
    metadata:
      labels:
        app: ai-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
      - name: ai-web
        image: ai-web:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /app/public/data
      volumes:
      - name: data
        emptyDir: {} 