apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - pv-pvc.yaml

commonLabels:
  app: ai-products-navigator
  environment: production

namespace: ai-products 