apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-products-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/ai-products
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-products-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 